import Head from 'next/head'
import { Inter } from 'next/font/google'
import Navbar from './components/Navbar'
import { useRouter } from 'next/router'
import Footer from './components/Footer'
import setUserinfo from '../helpers/token'
import { useEffect } from 'react'
import jwtDecode from 'jwt-decode'
import emailjs from '@emailjs/browser';
import { useRef, useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const router=useRouter()
  let userinfo;
  const form = useRef();
  const [mounted,setMounted]=useState(false)

  useEffect((userinfo) => {
    setMounted(true)
    if (localStorage.token) {
      const jwt = localStorage.getItem("token");
      setUserinfo(jwt);
      userinfo = jwtDecode(jwt);
      console.log(userinfo)
      console.log(userinfo.id)
    
  }
   


  }, []); 
  
  const sendEmail = (e) => {
    e.preventDefault();

    emailjs.sendForm('service_105ovjj', 'template_jxwyisj', form.current, 'm-nTF6BspaZIaWyhQ')
      .then((result) => {
          console.log(result.text);
      }, (error) => {
          console.log(error.text);
      });
  };
  if (mounted){
    if (localStorage.token) {
      const jwt = localStorage.getItem("token");
      setUserinfo(jwt);
      userinfo = jwtDecode(jwt);
      console.log(userinfo)
      console.log(userinfo.id)
    
  }



  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <main>
      <Navbar/>
      <div className='overall'>
      <img className='hero-image' src='./it.jpg'/>
      <div style={{display:'flex', flexDirection:'column', gap:50}}>
        <h2><span style={{color:'#7A86F2'}}>UniWeb </span>- каждый отчет может стать частью портфолио</h2>
        <div style={{display:'flex', justifyContent:'space-around'}}>
          <div style={{display:'flex', flexDirection:'column', gap:4, alignItems:'center'}}>
            <img className='small-image' src='./reposotory.png'/>

            <p style={{textAlign:'center'}}>Онлайн репозиторий</p>
          </div>
          <div  style={{display:'flex', flexDirection:'column', gap:4, alignItems:'center'}}>
            <img className='small-image' src='./check.png'/>

            <p style={{textAlign:'center'}}>Комфортная проверка</p>
          </div>
          <div  style={{display:'flex', flexDirection:'column', gap:4, alignItems:'center'}}>
            <img className='small-image' src='./update.png'/>

            <p style={{textAlign:'center'}}>Обновления и дополнения</p>
          </div>
        </div>
        <button onClick={()=>router.push('#email')} className='more-button'><span>Узнать больше</span><img style={{height:36}} src='./more.png'/></button>

      </div>
   
      
      </div>
      <div id="email" className='team-info' style={{display:'flex',flexDirection:'column', alignItems:'center', gap:10}}>
        <span>Заинтересовался?</span>
        <span>Стань частью нашей команды!
</span>


<form ref={form} onSubmit={sendEmail} style={{alignSelf:'center',display:'flex', justifyContent:'center',flexDirection:'column', margin:6, gap:10}}>
      <p>Ваше Имя</p>
      <input className='custom-input' type="text" name="user_name" />
      <p>Ваш Email</p>
      <input className='custom-input' type="email" name="myemail" />
      <p>Сообщение</p>
      <textarea name="message" />
      <button type='submit' className='send-button'>Отправить</button>
    </form>
  
        <img  className='team' src='./emil.png'/>
        </div>
      
      <Footer/>
    </main>
    </>
  )  }
  else{
    return null
  }
}
